#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 25, 2021 01:28:31 PM JST  platform: Windows NT

import sys
import libscrc
from tkinter import messagebox

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True


def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top


def set_Tk_var():
    global CRC_entry_label, CRC_display_label

    CRC_entry_label = tk.StringVar()
    CRC_display_label = tk.StringVar()


def display_CRC():
    user_input = CRC_entry_label.get()

    if not user_input:
        messagebox.showwarning(
            'Empty Field', 'Please enter the values to the entry box')

    else:
        crc16 = libscrc.modbus(user_input.encode("utf-8"))
        crc16 = hex(crc16)[2:]
        crc16 = str(crc16).upper()
        print(crc16)
        CRC_display_label.set(crc16)


def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None


if __name__ == '__main__':
    import CRC
    CRC.vp_start_gui()
